//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aula4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int idcli { get; set; }
        public string nomecli { get; set; }
        public string categoria { get; set; }
        public string fotopath { get; set; }
    }
}
